# Generated by Django 5.1.7 on 2025-03-19 15:15

import django.core.validators
import validators.socials
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_currency_auto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='github',
            field=models.CharField(blank=True, default='', help_text='Example: https://github.com/juanperez', max_length=100, validators=[validators.socials.validate_github], verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Example: https://mx.linkedin.com/in/juanperez', max_length=100, validators=[validators.socials.validate_linkedin], verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Example: @juanperez', max_length=100, validators=[validators.socials.validate_twitter], verbose_name='Twitter (X)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='github',
            field=models.CharField(blank=True, default='', help_text='Example: https://github.com/juanperez', max_length=100, validators=[validators.socials.validate_github], verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Example: https://mx.linkedin.com/in/juanperez', max_length=100, validators=[validators.socials.validate_linkedin], verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Example: @juanperez', max_length=100, validators=[validators.socials.validate_twitter], verbose_name='Twitter (X)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='github',
            field=models.CharField(blank=True, default='', help_text='Example: https://github.com/juanperez', max_length=100, validators=[validators.socials.validate_github], verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin',
            field=models.CharField(blank=True, default='', help_text='Example: https://mx.linkedin.com/in/juanperez', max_length=100, validators=[validators.socials.validate_linkedin], verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='lead',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Example: @juanperez', max_length=100, validators=[validators.socials.validate_twitter], verbose_name='Twitter (X)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(help_text='Use comma to separate Emails.', max_length=200, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(help_text='Use comma to separate Emails.', max_length=200, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title / Position'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(help_text='Use comma to separate Emails.', max_length=200, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title / Position'),
        ),
    ]
